// <auto-generated />
using System;
using Game.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.API.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20230409132339_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.API.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a0ab9b7-2164-47a3-b665-b3a69d544e6f"),
                            Description = "A dagger crafted from the tooth of a Pure Silver Dragon.",
                            Name = "Dagon",
                            Timestamp = new DateTime(2023, 4, 9, 13, 23, 39, 45, DateTimeKind.Utc).AddTicks(6112)
                        },
                        new
                        {
                            Id = new Guid("30d51435-fd1b-4d94-a2ea-b848df16b74c"),
                            Description = "A sword crafted from the talon of a Pure Silver Dragon.",
                            Name = "Yasha",
                            Timestamp = new DateTime(2023, 4, 9, 13, 23, 39, 45, DateTimeKind.Utc).AddTicks(6127)
                        },
                        new
                        {
                            Id = new Guid("e1fab68c-cce8-40bf-9f42-e37f9f05fe61"),
                            Description = "A bow crafted from the wing of a Pure Silver Dragon.",
                            Name = "Buriza",
                            Timestamp = new DateTime(2023, 4, 9, 13, 23, 39, 45, DateTimeKind.Utc).AddTicks(6182)
                        },
                        new
                        {
                            Id = new Guid("7fcf4f3b-01c6-4b92-8a57-2739144b29a3"),
                            Description = "An armor crafted from the scales of a Pure Silver Dragon.",
                            Name = "Vanguard",
                            Timestamp = new DateTime(2023, 4, 9, 13, 23, 39, 45, DateTimeKind.Utc).AddTicks(6187)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
