// <auto-generated />
using System;
using Game.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.API.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20230419123247_Initialize")]
    partial class Initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.API.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e438fd4c-8a72-46ea-a5e8-3c4df850b6d9"),
                            Description = "A dagger crafted from the tooth of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Dagon",
                            Price = 0.99m,
                            Timestamp = new DateTime(2023, 4, 19, 12, 32, 47, 232, DateTimeKind.Utc).AddTicks(6027),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("6b40b230-c6c4-40a4-92bf-01db943d7d2c"),
                            Description = "A sword crafted from the talon of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Yasha",
                            Price = 1.99m,
                            Timestamp = new DateTime(2023, 4, 19, 12, 32, 47, 232, DateTimeKind.Utc).AddTicks(6044),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("fe149d4f-00e5-468c-8a1c-12408176ac53"),
                            Description = "A bow crafted from the wing of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Buriza",
                            Price = 2.99m,
                            Timestamp = new DateTime(2023, 4, 19, 12, 32, 47, 232, DateTimeKind.Utc).AddTicks(6051),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("383b3d10-3f46-4c85-b91a-a4d19e028969"),
                            Description = "A shield crafted from the scales of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Vanguard",
                            Price = 3.99m,
                            Timestamp = new DateTime(2023, 4, 19, 12, 32, 47, 232, DateTimeKind.Utc).AddTicks(6057),
                            Type = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
