// <auto-generated />
using System;
using Game.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.API.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game.API.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0fe99fbe-4def-46e7-a51d-c60f55324dfe"),
                            Category = 0,
                            Description = "A dagger crafted from the tooth of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Dagon",
                            Price = 0.99m,
                            Timestamp = new DateTime(2023, 4, 17, 6, 28, 3, 143, DateTimeKind.Utc).AddTicks(5897)
                        },
                        new
                        {
                            Id = new Guid("d3336881-b66f-444b-b185-b9e4586fb161"),
                            Category = 1,
                            Description = "A sword crafted from the talon of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Yasha",
                            Price = 1.99m,
                            Timestamp = new DateTime(2023, 4, 17, 6, 28, 3, 143, DateTimeKind.Utc).AddTicks(5914)
                        },
                        new
                        {
                            Id = new Guid("3539245d-2b2a-4132-b5f0-8747b4ea89de"),
                            Category = 2,
                            Description = "A bow crafted from the wing of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Buriza",
                            Price = 2.99m,
                            Timestamp = new DateTime(2023, 4, 17, 6, 28, 3, 143, DateTimeKind.Utc).AddTicks(5920)
                        },
                        new
                        {
                            Id = new Guid("d3d1beee-2a78-4f86-9573-b2f4d65cd9db"),
                            Category = 3,
                            Description = "A shield crafted from the scales of a Pure Silver Dragon.",
                            Element = 4,
                            Name = "Vanguard",
                            Price = 3.99m,
                            Timestamp = new DateTime(2023, 4, 17, 6, 28, 3, 143, DateTimeKind.Utc).AddTicks(5926)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
