### Base URL
@host = http://localhost:5000

### Documented Response
# 201 Created
POST  {{host}}/api/item
Content-Type: application/json

{
    "name": "Cuirass",
    "description": "An armor crafted from the scales of a Pure Silver Dragon.",
    "category": "4",
    "element": "4",
    "price": "4.99"
}

### Documented Response
# 400 Bad Request
POST  {{host}}/api/item
Content-Type: application/json

{
    "name": "",
    "description": "",
    "category": "",
    "element": "",
    "price": ""
}
